import { useEffect, useState } from 'react';
import API from '../services/api';
import { Lightbulb, Sparkles, Target, Zap, Loader2, Brain, ChevronRight, Activity } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Recommendation() {
  const userId = localStorage.getItem('userId');
  const [recs, setRecs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState(null);

  useEffect(() => {
    // Parallel fetch for recommendations and stats
    const fetchData = async () => {
      try {
        const [recsRes, statsRes] = await Promise.all([
          API.get(`/recommendation/${userId}`),
          API.get(`/userStats/${userId}`)
        ]);
        setRecs(Array.isArray(recsRes.data) ? recsRes.data : []);
        setStats(statsRes.data);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [userId]);

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center">
        <Loader2 className="animate-spin text-[var(--accent-primary)]" size={48} />
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in duration-700 max-w-6xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 border-b border-[var(--border-color)] pb-6">
         <div>
            <h1 className="text-3xl font-bold flex items-center pro-text-main">
                <Brain className="text-[var(--accent-primary)] mr-3" size={32} />
                Neural Prescriptions
            </h1>
            <p className="pro-text-muted mt-2">Personalized optimization path generated by the Gemini Engine.</p>
         </div>
         {stats && (
           <div className="flex items-center space-x-4 bg-[var(--bg-card)] p-4 rounded-2xl border border-[var(--border-color)] shadow-sm">
             <div className="text-right">
                <p className="text-[10px] pro-text-muted uppercase font-bold tracking-widest">Global Rank</p>
                <p className="text-lg font-bold pro-text-main">#412 <span className="text-[var(--accent-primary)] text-xs font-normal">Top 12%</span></p>
             </div>
             <div className="h-8 w-[1px] bg-[var(--border-color)]"></div>
             <div className="text-right">
                <p className="text-[10px] pro-text-muted uppercase font-bold tracking-widest">Brain Power</p>
                <p className="text-lg font-bold pro-text-main">{stats.xp || 0} <span className="text-[var(--accent-primary)] text-xs font-normal">XP</span></p>
             </div>
           </div>
         )}
      </div>

      {/* Summary Header */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 glass-panel p-8 relative overflow-hidden flex flex-col justify-center">
           <div className="absolute top-0 right-0 w-64 h-64 bg-[var(--accent-primary)] opacity-5 blur-[80px] rounded-full"></div>
           <h2 className="text-2xl font-bold pro-text-main mb-4 flex items-center">
             <Sparkles className="text-violet-400 mr-3" size={24} />
             Cognitive Roadmap
           </h2>
           <p className="pro-text-muted leading-relaxed max-w-xl">
             Your neural profile suggests a high aptitude for {stats?.categoryStats?.[1]?.subject || 'Logic'}, but there is slight latency in {stats?.categoryStats?.[0]?.subject || 'Memory'} retrieval. Following these prescriptions will normalize your performance across all cognitive sectors.
           </p>
        </div>
        <div className="glass-panel p-6 bg-[var(--accent-glow)] border-[var(--border-color)] flex flex-col justify-between">
           <div>
             <h3 className="pro-text-muted font-bold uppercase tracking-widest text-xs mb-4 opacity-80">Current Focus</h3>
             <p className="pro-text-main text-lg font-bold leading-tight italic">Normalize Synaptic Latency in Speed Categories</p>
           </div>
           <Link to="/problems" className="mt-6 flex items-center text-[var(--accent-primary)] hover:opacity-80 font-bold text-sm transition group">
              View Problem Set <ChevronRight size={16} className="ml-1 group-hover:translate-x-1 transition-transform" />
           </Link>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {recs.map((rec, idx) => {
          const priority = (rec.priority || '').toLowerCase();
          
          return (
            <div key={idx} className="glass-card hover:bg-[var(--bg-card)] transition-all duration-300 group flex flex-col min-h-[300px]">
              <div className="flex justify-between items-start mb-6">
                 <div className={`p-3 rounded-xl border flex items-center justify-center ${priority === 'high' ? 'bg-red-500/10 border-red-500/20 text-red-500' : 'bg-[var(--accent-glow)] border-[var(--border-color)] text-[var(--accent-primary)]'}`}>
                   {rec.category === 'Memory' ? <Brain size={24} /> : rec.category === 'Logic' ? <Target size={24} /> : <Activity size={24} />}
                 </div>
                 {priority === 'high' && (
                    <span className="flex items-center text-[10px] font-black uppercase tracking-tighter text-red-500 bg-red-500/5 px-2 py-1 rounded border border-red-500/20 shadow-sm">
                      High Priority
                    </span>
                 )}
              </div>

              <h3 className="text-xl font-bold pro-text-main mb-3 group-hover:text-[var(--accent-primary)] transition-colors">{rec.title}</h3>
              <p className="pro-text-muted text-sm leading-relaxed mb-6 flex-1 italic">
                "{rec.description}"
              </p>
              
              <Link 
                to={rec.category ? `/problems?category=${rec.category}` : "/problems"} 
                className="flex items-center justify-center w-full py-3 bg-[var(--bg-card)] hover:bg-[var(--border-color)] pro-text-main rounded-xl text-xs font-bold uppercase tracking-widest transition border border-[var(--border-color)]"
              >
                Execute Prescription
              </Link>
            </div>
          );
        })}
      </div>

      {recs.length === 0 && (
        <div className="flex flex-col items-center justify-center p-20 glass-panel">
           <Zap size={64} className="pro-text-muted opacity-20 mb-6 animate-pulse" />
           <h3 className="text-2xl font-bold pro-text-main mb-2">Neural Engine Initializing</h3>
           <p className="pro-text-muted text-center max-w-md">The Gemini Engine requires more data points to generate accurate prescriptions. Solve 3 more problems to calibrate.</p>
        </div>
      )}
    </div>
  );
}
